from django.urls import path
from .views import google_login
from django.urls import path, include
from .views import *
from .views import SmartbiteDashboardAPIView
from .views import AnalyticsAPIView
urlpatterns=[
    path('admin-login/',admin_login_api),
    path('add-category/',add_category),
    path('categories/',list_categories),
    path('foods/',list_foods),
    path('add-food-item/',add_food_item),
    path('food_search/',food_search),
    path('random_foods/', random_foods),
    path('register/', register_user),
    path('login/',login_user),
    path('foods/<int:id>/',food_detail),
    path('cart/add/',add_to_cart),
    path('cart/<int:user_id>/',get_cart_items),
    path('cart/update_quantity/',update_cart_quantity),
    path('cart/delete/<int:order_id>/',delete_cart_item),
    path('place_order/',place_order),
      # path('create_razorpay_order/',create_razorpay_order),
    path('orders/<int:user_id>/',user_orders),
    path('orders/by_order_number/<str:order_number>/',order_by_order_number),
    path('order_address/<str:order_number>/',get_order_address),
    path('invoice/<str:order_number>/',get_invoice),
    path('user/<int:user_id>/',get_user_profile),
    path('user/update/<int:user_id>/',update_user_profile),
    path('change_password/<int:user_id>/',change_password),
    path('orders-not-confirmed/',orders_not_confirmed),
    path('orders_confirmed/',orders_confirmed),
    path('foodbeing_prepared/',foodbeing_prepared),
    path('food-pickup/',Food_pickup),
    path('food_delivered/',Food_delivered),
    path('order_cancelled/',order_cancelled),
    path('all_orders/',all_orders),
    path('order-between-dates/',order_between_dates),
    path('view-order-detail/<str:order_number>/',view_order_detail),
    path('update_order_status/',update_order_status),
    path('search-orders/',search_orders),
    path('category/<int:id>/',category_detail),
    path('delete-food/<int:id>/',delete_food),
    path('edit-food/<int:id>/',edit_food),
    path('users/',list_users),
    path('delete-users/<int:id>/',delete_users),
    path('dashboard_metrics/',dashboard_metrics),
    # path('monthly_sales_summary/',monthly_sales_summary),
    path('google-login/', google_login),
    path('wishlist/add/', add_to_wishlist),
    path('wishlist/remove/', remove_from_wishlist),
    path('wishlist/<int:user_id>/', get_wishlist),
    path('track_order/<str:order_number>/', track_order),
    path('cancel_order/<str:order_number>/', cancel_order),
    path('reviews/add/<int:food_id>/', add_review),
    path('reviews/<int:food_id>/', food_reviews),
    path('review_edit/<int:id>/', review_detail),
    path('food_rating_summary/<int:food_id>/',food_rating_summary),
    path('all_reviews/',all_reviews),
    path('delete_review/<int:id>/',all_reviews),
    path('chat/', chat_api),

    #----------------insights hub urls----------------------
    path( "smartbite/dashboard/",SmartbiteDashboardAPIView.as_view()),
    path("smartbite/analytics/",AnalyticsAPIView.as_view()),
    path("smartbite/conflicts/",ConflictAPIView.as_view()),
    path("smartbite/notifications/",NotificationAPIView.as_view()),
    path("smartbite/search/",smartbite_search),
    path("smartbite/predictions/",PredictionAPIView.as_view()),
    path("smartbite/reviews/",ReviewAPIView.as_view()),
    
] 