# Generated by Django 5.2.8 on 2026-04-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0004_foodtracking_orderaddress_paymentdetail_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetail',
            old_name='cart_number',
            new_name='card_number',
        ),
    ]
