# Generated by Django 5.2.8 on 2026-04-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0005_rename_cart_number_paymentdetail_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_mode',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment')], max_length=20),
        ),
    ]
