# Generated by Django 5.2.8 on 2026-05-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0007_alter_review_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
