# Generated by Django 5.2.8 on 2026-05-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0011_remove_user_mobile_user_is_admin_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtracking',
            name='order',
        ),
        migrations.AddField(
            model_name='foodtracking',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
